#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
server_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.nginx-debian.html;
    server_name sabot-dev.tech;
    add_header X-Served-By $hostname;
    rewrite ^/redirect_me/$ www.google.com/ permanent;
    location / {
	try_files $uri $uri/ =404;
    }

    if ($request_filename ~ redirect_me){
	   rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}"
echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
