#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo touch /usr/share/nginx/html/error404.html
sudo chmod 777 /usr/share/nginx/html/error404.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/error404.html

server_config=\
"server {
       listen 80 default_server;
       listen [::]:80 default_server;

       server_name _;
       add_header X-Served-By $hostname;

       root /var/www/example.com;
       index index.html;

       location / {
               try_files $uri $uri/ =404;
       }
       if (\$request_filename ~ redirect_me){
	        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
       }
       error_page 404 /404.html;
       location = /404.html {
		 internal;
       }
}"

sudo chmod 777 /etc/nginx/sites-enabled/default
echo "$server_config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
