#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy=2.5.\*

sed -i '/errorfile 504/a listen sabot-dev' /etc/haproxy/haproxy.cfg
sed -i '/listen sabot-dev/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 786-web-01 34.139.214.81:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 786-web-01 34.139.214.81:80 check/a         server 786-web-02 35.196.47.120:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy

